### PR TITLE
GSREN3D-301: FooterArea : use footer from common library

### PR DESCRIPTION
**Pull request by toni-garcia-camptocamp**
GSREN3D-301: FooterArea : use footer from common library

### JIRA issue.

https://jira.camptocamp.com/browse/GSREN3D-301

### Description

To install the common library you can run the following commands : 
npm install
If npm install doesn't work : npm i https://github.com/sigrennesmetropole/cooperation_jn_common_ui.git

All the installation instruction of common library will be in READ ME of this repo : https://github.com/sigrennesmetropole/cooperation_jn_common_ui

### CODE REVIEW

**Comment by ismailsunni** [comment]
Seems there is something is missing with the layout:

Solar App
image

Trambus App
image

**Comment by ismailsunni** [comment]
Hi @toni-garcia-camptocamp 

I tried to use the common library from my local computer. I tried your instruction with `npm link`, but it can't find it, and I got this error message:
```
isunni@wrk136:~/dev/js/cooperation_jn_solar ((HEAD detached at origin/test-library-common))$ npm link cooperation_jn_common_ui
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/cooperation_jn_common_ui - Not found
npm ERR! 404 
npm ERR! 404  'cooperation_jn_common_ui@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
```

is there something that I need to do first? Perhaps we can have a short session to show how to do it.

**Comment by toni-garcia-camptocamp** [comment]
> Hi @toni-garcia-camptocamp
> 
> I tried to use the common library from my local computer. I tried your instruction with `npm link`, but it can't find it, and I got this error message:
> 
> ```
> isunni@wrk136:~/dev/js/cooperation_jn_solar ((HEAD detached at origin/test-library-common))$ npm link cooperation_jn_common_ui
> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/cooperation_jn_common_ui - Not found
> npm ERR! 404 
> npm ERR! 404  'cooperation_jn_common_ui@*' is not in this registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404 
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> 
> npm ERR! A complete log of this run can be found in:
> ```
> 
> is there something that I need to do first? Perhaps we can have a short session to show how to do it.

Like i say Yohann, you have to run "npm link" first in cooperation_jn_common_ui first 
But yes we can make a call to fix that

**Comment by toni-garcia-camptocamp** [comment]
> time? I think we will forgot if we are not doing

Yes we have to update solar and trambus at the same time when we will add a new component to common library

**Pull request closed without merging**
